spring:

 application:

  name: ConfigServer

 cloud:

  config:

   server:

    git:

     uri: https://github.com/dikshitbcrec/cofigtest.git

     username: dikshitbcrec@gmail.com

     password: 9504149645

server:

 port: 8686
